Import Important Libraries

In [101]:
import pandas as pd
import numpy as np

In [102]:
df1 = pd.read_csv("/content/soil_measures.csv")

EDA explanatory data analysis

In [103]:
df1

        N   P   K        ph    crop
0      90  42  43  6.502985    rice
1      85  58  41  7.038096    rice
2      60  55  44  7.840207    rice
3      74  35  40  6.980401    rice
4      78  42  42  7.628473    rice
...   ...  ..  ..       ...     ...
2195  107  34  32  6.780064  coffee
2196   99  15  27  6.086922  coffee
2197  118  33  30  6.362608  coffee
2198  117  32  34  6.758793  coffee
2199  104  18  30  6.779833  coffee

[2200 rows x 5 columns]

In [104]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   N       2200 non-null   int64
 1   P       2200 non-null   int64
 2   K       2200 non-null   int64
 3   ph      2200 non-null   float64
 4   crop    2200 non-null   object
dtypes: float64(1), int64(3), object(1)
memory usage: 86.1+ KB

In [105]:
df1

        N   P   K        ph    crop
0      90  42  43  6.502985    rice
1      85  58  41  7.038096    rice
2      60  55  44  7.840207    rice
3      74  35  40  6.980401    rice
4      78  42  42  7.628473    rice
...   ...  ..  ..       ...     ...
2195  107  34  32  6.780064  coffee
2196   99  15  27  6.086922  coffee
2197  118  33  30  6.362608  coffee
2198  117  32  34  6.758793  coffee
2199  104  18  30  6.779833  coffee

[2200 rows x 5 columns]

In [106]:
df1['crop'].unique()

array(['rice', 'maize', 'chickpea', 'kidneybeans', 'pigeonpeas',
       'mothbeans', 'mungbean', 'blackgram', 'lentil', 'pomegranate',
       'banana', 'mango', 'grapes', 'watermelon', 'muskmelon', 'apple',
       'orange', 'papaya', 'coconut', 'cotton', 'jute', 'coffee'],
      dtype=object)

In [107]:
df1.isnull().sum()

N       0
P       0
K       0
ph      0
crop    0
dtype: int64

Import label encoder to convert the crop column to numerical labels

In [108]:
df1['crop'].unique()

array(['rice', 'maize', 'chickpea', 'kidneybeans', 'pigeonpeas',
       'mothbeans', 'mungbean', 'blackgram', 'lentil', 'pomegranate',
       'banana', 'mango', 'grapes', 'watermelon', 'muskmelon', 'apple',
       'orange', 'papaya', 'coconut', 'cotton', 'jute', 'coffee'],
      dtype=object)

In [109]:
from sklearn.preprocessing import LabelEncoder

label = LabelEncoder()

In [110]:
df1['crop'] = label.fit_transform(df1['crop'])

In [111]:
df1['crop']

0       20
1       20
2       20
3       20
4       20
        ..
2195     5
2196     5
2197     5
2198     5
2199     5
Name: crop, Length: 2200, dtype: int64

In [112]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   N       2200 non-null   int64
 1   P       2200 non-null   int64
 2   K       2200 non-null   int64
 3   ph      2200 non-null   float64
 4   crop    2200 non-null   int64
dtypes: float64(1), int64(4)
memory usage: 86.1 KB

In [113]:
#df1['crop'] = df1['crop'].astype(int)

In [114]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   N       2200 non-null   int64
 1   P       2200 non-null   int64
 2   K       2200 non-null   int64
 3   ph      2200 non-null   float64
 4   crop    2200 non-null   int64
dtypes: float64(1), int64(4)
memory usage: 86.1 KB

In [115]:
df1['crop'].value_counts()

crop
20    100
11    100
3     100
9     100
18    100
13    100
14    100
2     100
10    100
19    100
1     100
12    100
7     100
21    100
15    100
0     100
16    100
17    100
4     100
6     100
8     100
5     100
Name: count, dtype: int64

Data Splitting

In [126]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [127]:
x = df1.drop(columns = ['crop'])
y = df1['crop']

model training

In [129]:
# Separate features and target
#x = crops.drop('crop', axis=1)
#y = crops['crop']

# Store the best feature and its score
best_feature = None
best_score = 0

# Evaluate each feature individually
for feature in x.columns:
    x_feature = x[[feature]]
    x_train, x_test, y_train, y_test = train_test_split(x_feature, y, test_size=0.2, random_state=42)
    model = LogisticRegression(max_iter=200)
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    score = metrics.accuracy_score(y_test, y_pred)
    print('feature : ' , feature)
    print('score: ' , score)
    if score > best_score:
        best_score = score
        best_feature = feature

# Store the result in the required format
best_predictive_feature = {best_feature: best_score}

# Display the result
best_predictive_feature

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

feature :  N
score:  0.15681818181818183

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

feature :  P
score:  0.19545454545454546

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

feature :  K
score:  0.2818181818181818
feature :  ph
score:  0.09772727272727273

{'K': 0.2818181818181818}